# Generated by Django 3.1.7 on 2021-12-10 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20211210_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 13, 42, 22, 808135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 13, 42, 22, 808135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 13, 42, 22, 808135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 13, 42, 22, 808135, tzinfo=utc)),
        ),
    ]
