# Generated by Django 3.1.7 on 2021-12-11 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20211210_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 1, 25, 248473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 1, 25, 248473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 1, 25, 248473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 1, 25, 248473, tzinfo=utc)),
        ),
    ]
